-- MySQL Script generated by MySQL Workbench
-- Tue Aug  8 15:33:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iq-defcon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iq-defcon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iq-defcon` DEFAULT CHARACTER SET utf8 ;
USE `iq-defcon` ;

-- -----------------------------------------------------
-- Table `iq-defcon`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iq-defcon`.`user` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iq-defcon`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iq-defcon`.`comment` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `comment` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE USER 'iq-defcon' IDENTIFIED BY 'password';

GRANT ALL ON `iq-defcon`.* TO 'iq-defcon';
GRANT SELECT ON TABLE `iq-defcon`.* TO 'iq-defcon';
GRANT SELECT, INSERT, TRIGGER ON TABLE `iq-defcon`.* TO 'iq-defcon';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `iq-defcon`.* TO 'iq-defcon';
GRANT EXECUTE ON ROUTINE `iq-defcon`.* TO 'iq-defcon';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
